### ISSUE TITLE
BooleanSlider not compatible with Mendix 8.4.0

### ISSUE THREAD

**Issue by bkoppen** [mendix/BooleanSlider#10]
Hi there,

I wanted to update to Mendix 8.4.0 but unfortunately the boolean slider doesn't work anymore in this version. Is it possible to fix this?

**Comment by MJLan1** [comment]
Also 8.5.0 not compatible unfortunately.

**Comment by JelteMX** [comment]
This widget is considered deprecated, we suggest you use the [Switch](https://appstore.home.mendix.com/link/app/50324/) widget.
