### ISSUE TITLE
Error when using the Boolean Widget.

### ISSUE THREAD

**Issue by rvanosnabrugge** [mendix/BooleanSlider#5]
When using the Boolean slider widget, I receive the following error in the browser console: "An error occured while handling queued requests: Cannot set property "textContent" of null.".

You will be able to reproduce the error as follows: open a (popup) page with the boolean slider widget, close the page and repeat the previous steps (open and close again). The second time you tried to close the page, the error occurs.

If you have any questions, please let me know!

**Comment by tieniber** [comment]
@rvanosnabrugge, can you try the new MPK in your project and see if it resolves your issue. Seems to work in my testing.

@JelteMX , I put in a workaround for this issue as it was causing trouble in one of my projects as well. It seems that we lose our references to this.trueNode and this.falseNode when we get a callback from an attribute listener. Perhaps something wrong with _TemplatedMixin, or perhaps we're not destroying the widget properly?

I resolved this by adding _trueNode and _falseNode variables and setting them in PostCreate.

**Comment by rvanosnabrugge** [comment]
The new MPK does not give the error, so I think your fix works =)

Met vriendelijke groet,
Richard van Osnabrugge

**Comment by JelteMX** [comment]
@tieniber thanks, I'll check it out. Maybe we need to restructure the widget. I've promised @rvanosnabrugge to take a look at it either this week or next week. Thanks for the workaround right now
