### ISSUE TITLE
Boolean Slider Widget Toggle issue

### ISSUE THREAD

**Issue by salmaMphasis** [mendix/BooleanSlider#8]
Hi,

I am using boolean slider widget and calling services on enable and disable of slider accordingly. But when i toggle the slider continuously or toggle in the middle of the widget , it is stopping in the middle.

 

Is there any way to solve this?

 

Appreciate a prompt response.

**Comment by JelteMX** [comment]
This widget is considered deprecated, we suggest you use the [Switch](https://appstore.home.mendix.com/link/app/50324/) widget.
